require 'chef_metal'
require 'chef_metal_fog/drivers/rackspace'
require 'chef_metal_fog/drivers/openstack'
require 'chef_metal_fog/drivers/digital_ocean'
require 'chef_metal_fog/drivers/aws'
require 'chef_metal_fog/drivers/cloudstack'
require 'chef_metal_fog/recipe_dsl'
