# A sample Gemfile
source "https://rubygems.org"

gem 'chef-provisioning', :github => 'chef/chef-provisioning'

gem 'chef-provisioning-vagrant', :github => 'chef/chef-provisioning-vagrant'
gem 'chef-provisioning-fog', :github => 'chef/chef-provisioning-fog'
gem 'chef-provisioning-aws', :github => 'chef/chef-provisioning-aws'
gem 'chef-provisioning-azure', :github => 'chef/chef-provisioning-azure'

#gem 'chef-provisioning-docker', :github => 'chef/chef-provisioning-docker'
#gem 'chef-provisioning-lxc', :github => 'chef/chef-provisioning-lxc' if RUBY_PLATFORM.downcase.include?("linux")
#gem 'chef-provisioning-hanlon', :github => 'chef/chef-provisioning-hanlon'

gem 'chef', '~> 11.16'

gem 'mixlib-shellout'
gem 'mixlib-config'
gem 'mixlib-cli'

gem 'rspec_junit_formatter'
gem 'rspec-instafail'

gem 'yard'
gem 'retryable', '~> 1.3.6'
gem 'berkshelf', '~> 3.2.0'
