# A sample Gemfile
source "https://rubygems.org"

#gem 'chef-provisioning', :github => 'opscode/chef-provisioning'
gem 'chef-provisioning', :github => 'opscode/chef-provisioning'

gem 'chef-provisioning-vagrant', :github => 'opscode/chef-provisioning-vagrant'
gem 'chef-provisioning-fog', :github => 'opscode/chef-provisioning-fog'
gem 'chef-provisioning-aws', :github => 'opscode/chef-provisioning-aws'
#gem 'chef-provisioning-azure'

#gem 'chef-provisioning-docker', :github => 'opscode/chef-provisioning-docker'
#gem 'chef-provisioning-lxc', :github => 'opscode/chef-provisioning-lxc' if RUBY_PLATFORM.downcase.include?("linux")
#gem 'chef-provisioning-hanlon', :github => 'opscode/chef-provisioning-hanlon'

gem 'chef', :github => 'opscode/chef'

gem 'rspec_junit_formatter'
gem 'rspec-instafail'

gem 'yard'
gem 'retryable', '~> 1.3.6'
gem 'berkshelf', '~> 3.2.0'
